[Android auto] first instruction fix
mapbox/mapbox-navigation-android pull request #5825
Opened 2022-05-18 12:55 UTC by korshaknn

### Description

This PR fixes an issue when the first instruction is not played.
It's related to `libnavui-androidauto` module only and can be tested with 1Tap.
Also it might be useful to have some activity (or a separate test app?) in `examples` to test `libnavui-androidauto` module.

### issue details:
- when routes observer triggered we cancel previous voice instructions flow, create a new flow with a new instructions observer
- new instructions observer ^^ created too late and we lost the first instruction

### changes:
- start/stop listening for `routes`, `instructions`, `tripSessionState` on `attach`/`detach`
- pass values ^^ to flows stored in `MapboxAudioGuidanceServicesImpl`

2022-05-18 12:58 UTC, korshaknn commented
not sure about the changelog, do we need it?

2022-05-18 13:18 UTC, LukasPaczos commented
> not sure about the changelog, do we need it?

We have a separate file in [libnavui-androidauto/CHANGELOG.md](https://github.com/mapbox/mapbox-navigation-android/blob/main/libnavui-androidauto/CHANGELOG.md), could you move the note there?

2022-05-19 00:26 UTC, kmadsen commented
> Also it might be useful to have some activity (or a separate test app?) in examples to test libnavui-androidauto module.

Side note, yeah this is happening. We're consolidating 1tap, drop-in-ui, and android-auto implementations for audio guidance. Essentially, all examples will use the same implementation. Right now it is in transition, sorry the qa-test-app support at the moment is lacking.

2022-05-19 00:35 UTC, kmadsen commented on libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxVoiceInstructions.kt
> +        MapboxNavigationApp.registerObserver(this)
`MapboxNavigationApp.unregisterObserver(mapboxAudioGuidance)` should also unregister all of the underlying observers.

2022-05-19 00:40 UTC, kmadsen commented on libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxVoiceInstructions.kt
> +        MapboxNavigationApp.registerObserver(this)
The not-so-elegant solution would be to delete this `init` `registerObserver`. And then add the attach/detach to `MapboxAudioGuidanceImpl`

``` kotlin
MapboxAudioGuidanceImpl
...
    override fun onAttached(mapboxNavigation: MapboxNavigation) {
+        MapboxAudioGuidanceServices.mapboxVoiceInstructions().onAttached(mapboxNavigation)
        job = scope.launch { audioGuidanceFlow(mapboxNavigation).collect() }
    }

    override fun onDetached(mapboxNavigation: MapboxNavigation) {
+        MapboxAudioGuidanceServices.mapboxVoiceInstructions().onDetached(mapboxNavigation)
        job?.cancel()
        job = null
    }
```

2022-05-19 01:01 UTC, kmadsen requested changes
https://github.com/mapbox/mapbox-navigation-android/pull/5825/files#r876477888

Sorry it is a confusing because `MapboxCarApp` controls a single subscription by subscribing and never unsubscribing from `MapboxAudioGuidance` (at the moment).

MapboxAudioGuidance is not actually a singleton. Doing something like this should not leak subscriptions.
```

audioGuidance: MapboxAudioGuidance = MapboxAudioGuidanceImpl(...)
MapboxNavigationApp.registerObserver(audioGuidance)
MapboxNavigationApp.unregisterObserver(audioGuidance)
audioGuidance: MapboxAudioGuidance = MapboxAudioGuidanceImpl(...)
MapboxNavigationApp.registerObserver(audioGuidance)
MapboxNavigationApp.unregisterObserver(audioGuidance)
```

2022-05-19 07:05 UTC, korshaknn commented
@kmadsen thanks for the feedback!
> Is this the fix to convert the underlying flowables into hot flowable? Meaning, they stay subscribed even after the top level is unsubscribed.

yes, we need it because with cold flows we miss the first instruction.

> MapboxNavigationApp.unregisterObserver(mapboxAudioGuidance) should also unregister all of the observers it is responsible for.

fixed with 
```
override fun onAttached(mapboxNavigation: MapboxNavigation) {
        mapboxVoiceInstructions.registerObservers(mapboxNavigation)
        job = scope.launch { audioGuidanceFlow(mapboxNavigation).collect() }
}

override fun onDetached(mapboxNavigation: MapboxNavigation) {
        mapboxVoiceInstructions.unregisterObservers(mapboxNavigation)
        job?.cancel()
        job = null
}
```

also `MapboxVoiceInstructions` is not a `MapboxNavigationObserver` anymore, so we need to manually `register/unregister` observers like we do it in `MapboxAudioGuidanceImpl`.
I think we should be good with it at least for now, `MapboxVoiceInstructions` is only used in `MapboxAudioGuidanceImpl`.

2022-05-19 15:28 UTC, kmadsen approved these changes
LGTM

2022-05-19 15:37 UTC, Zayankovsky approved these changes

2022-05-19 15:37 UTC, Zayankovsky commented on libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxVoiceInstructions.kt
> +    fun unregisterObservers(mapboxNavigation: MapboxNavigation) {
Should we clear the state flows here?

2022-05-19 18:53 UTC, merged